archive_dir: archive

cams:
  summit:
    type: image  # image | stream
    url: "https://cameraftpapi.drivehq.com/api/Camera/LastImageaspx/shareID17403860/bwdsummit.jpg?"
  base:
    type: image
    url: "https://cameraftpapi.drivehq.com/api/Camera/LastImageaspx/shareID17403629/bwdbase.jpg?"
